### PR TITLE
(Issue 303) Modify blog post header layout

### LINKED ISSUE #303: Modify the layout/design of blog posts
Several changes to the blog post pages should be applied, to make it look like the image below:

- [x] Lead (excerpt) should appear under the title, with `opacity: .7; font-weight: 300; font-size: 1.5rem;`
- [x] Publication date should have a `font-weight: 400;`
- [x] Social media icons should be smaller, consider `font-size: 1.4em;`
- [x] Both Publication date/social icons should appear below the author(s) and translator(s). Consider spacing/margins as in the image below.
- [x] The body of the blog post should have the same font-family, but with `font-size: 1.25rem; line-height: 1.8;`
- [x] Margin of the page should be ~1.5rem as suggested in issue #300 

image

### PR DESCRIPTION
**Pull request by zjbarg**
Fixes #303 

### Changes to the social icons component:
-  Added 2 props: size, ignore-size.
- If neither is provided, the component will show as is now. (font-awesome size = 2x)
- If size is provided (sm, lg, 5x), font awesome size will be applied.
- If ignore-size is set to true, null will be passed to size on the icons so the font size can be simply set on the component as a whole by normal tailwind font size classes of any other means.

### CODE REVIEW

**Comment by ZaidBarghouthi** [comment]
@mahasneh, This is how it is looking on my device right now. What do you think. 
Should we change the vertical spacing between the sections?

Changed the title to bold although it wasn't mentioned in #303 

image

**Comment by ZaidBarghouthi** [comment]
Need someone to review the changes to the social icons components btw.

**Comment by mahasneh** [comment]
Hmm, I think this one was already handled in #331 can @wissamataleh confirm?

**Comment by wissamataleh** [comment]
Solved in Release v1.5.1

**Pull request closed without merging**
