### PR TITLE
(Issue 261) Show a disclaimer in non-statement blog posts

### PR DESCRIPTION
**Pull request by linuxjo**

### CODE REVIEW

**Comment by linuxjo** [comment]
@mahasneh @wissamataleh What were exactly the suggested edits here?

**Comment by wissamataleh** [comment]
> @mahasneh @wissamataleh What were exactly the suggested edits here? 

To change the styling to match the design

**Comment by linuxjo** [comment]
> To change the styling to match the design
> [#261 (comment)](https://github.com/jordanopensource/portal-web/issues/261#issuecomment-829060959)

@wissamataleh regarding the disclaimer text itself I have customized the style just as @mahasneh illustrated in the photo that he attached as a comment. Font size is also as mahasneh suggested (0.9rem). So now what should be changed is just the style of the hr tag, right? Otherwise I think that everything matches the suggested design. 

Check out Issa's image #287

**Comment by linuxjo** [comment]
> To change the styling to match the design
> [#261 (comment)](https://github.com/jordanopensource/portal-web/issues/261#issuecomment-829060959)

@wissamataleh  regarding the disclaimer text itself I have customized the style just as @mahasneh illustrated in the photo that he attached as a comment. Font size is also as mahasneh suggested (0.9rem). So now what should be changed is just the style of the hr tag, right? Otherwise I think that everything matches the suggested design.

**Pull request closed without merging**
