### PR TITLE
(Issue 213) Arabic names of Gregorian months should be Syriac translation

### LINKED ISSUE #213: Arabic names of Gregorian months should be Syriac
Arabic names of Gregorian months should be Syriac, not Latin, like كَانُون ٱلثَّانِي, شُبَاط, etc. and not يناير, etc.

### PR DESCRIPTION
**Pull request by ZaidBarghouthi**
Fixes #213 

Unfortunately, momentjs doesn't implement any Arabic locale with Syriac names for Gregorian months. I might end up submitting PR. 

In the mean time the following changes were implemented.

1. Removed unused date filters as it doesn't make since to fix something that is not used.
2. Used Intl.DateTimeFormat with locales 'ar-JO' and 'en-UK' to get the dates as shown in the pics below.

image
image
image

### CODE REVIEW

**Comment by ZaidBarghouthi** [comment]
Fixes #213

**Comment by ZaidBarghouthi** [comment]
Kindly link Issue #213 manually as it is not allowing me to link it.

**Comment by wissamataleh** [comment]
@ZaidBarghouthi Looks good :) Can you do also fix the formatting in `EventListPrevious` components?

**Comment by ZaidBarghouthi** [comment]
@wissamataleh, done. 

image

Fixed for upcoming and previous events. 

Btw, there are other places where moment is used directly in the component to format the data, but I can't seem to find the pages where these components are used. They are `ActivityPreview`, `SocialFeed`.

I'm not sure if I should try to fixed them as they are not showing.

Let me know.

**Comment by wissamataleh** [comment]
> @wissamataleh, done.
> 
> image
> 
> Fixed for upcoming and previous events.
> 
> Btw, there are other places where moment is used directly in the component to format the data, but I can't seem to find the pages where these components are used. They are `ActivityPreview`, `SocialFeed`.
> 
> I'm not sure if I should try to fixed them as they are not showing.
> 
> Let me know.

@ZaidBarghouthi Thanks, for the `ActivityPreview` it should be edited as well, see "Highlighted Activities" section in [this page](https://www.josa.ngo/programs/5/open-source-software). But for the `SocialFeed` there's no need to fix it, the component will be refactored if we plan to use it again.

**Comment by ZaidBarghouthi** [comment]
@wissamataleh, Done.
 
Date will show as one of these:

- كانون الثاني ٢٠٢٠
- كانون الثاني و شباط ٢٠٢٠
- كانون الثاني إلى آذار ٢٠٢٠
- تشرين الثاني ٢٠٢٠ إلى شباط ٢٠٢١

**Review by wissamataleh — APPROVED** [review]

**Comment by wissamataleh** [comment]
@ZaidBarghouthi Great work, thanks.

**Pull request merged**
