### PR TITLE
(Issue 285) Add a default author image

### PR DESCRIPTION
**Pull request by linuxjo**

### CODE REVIEW

**Comment by mahasneh** [comment]
Which image was used as a placeholder?

**Comment by linuxjo** [comment]
@mahasneh I have created one. 
#A3D1E4 (Same color used as a background authors' images). 

static/images/icons/authorimage_default.png

**Comment by linuxjo** [comment]
@mahasneh Do you have a suggestion for a default author image?

**Comment by mahasneh** [comment]
The one you created looks more than ok

**Comment by linuxjo** [comment]
@mahasneh Great! However, a new one could be designed later. :D

**Review by wissamataleh — APPROVED** [review]

**Pull request merged**
