### PR TITLE
Change becomeAMember url

### PR DESCRIPTION
**Pull request by mohshbool**

### CODE REVIEW

**Comment by mahasneh** [comment]
@mohshbool Please take into account commit messages should have the first letter capitalized.

**Comment by mahasneh** [comment]
Fix branches should be merged into `development` first, after tested, they are merged into `main`.

**Review by mahasneh — CHANGES_REQUESTED** [review]
Fix branches should be merged into `development` first, after tested, they are merged into `main`.

**Comment by mohshbool** [comment]
> Fix branches should be merged into `development` first, after tested, they are merged into `main`.

Done!

**Pull request closed without merging**
