### PR TITLE
Add share functionality to dossiers

### LINKED ISSUE #298: Add share functionality to dossiers
Add share icons for dossiers as previously added to blogs...etc.

### PR DESCRIPTION
**Pull request by linuxjo**
resolves #298

### CODE REVIEW

**Comment by wissamataleh** [comment]
@linuxjo Please add it above the description as well

**Comment by linuxjo** [comment]
> @linuxjo Please add it above the description as well

@wissamataleh Ok

**Comment by geokhoury** [comment]
#### 📝Changed routes:


| [**/dossier/_slug**](https://portal-web-dgaw2vazv-josa.vercel.app/dossier/_slug) |
|:-:|
|<a href="https://portal-web-dgaw2vazv-josa.vercel.app/dossier/_slug">Screenshot of /dossier/_slug</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/KCB8VpFOBVbUh4Q9l1_nDw5TOQQdhtLLTyKA-sg9-4yhFSqiGZV1rr9XrqgVx9TwRM3PZ1WaHaucTlSNiopTrw.png">(view full size)</a> |







Commit 8225af0a6aff9b94e4386ccdd1d9497b9d229336 (https://portal-web-dgaw2vazv-josa.vercel.app).

**Comment by geokhoury** [comment]
#### 📝Changed routes:


| [**/dossier/_slug**](https://portal-web-a6bq1n9c8-josa.vercel.app/dossier/_slug) |
|:-:|
|<a href="https://portal-web-a6bq1n9c8-josa.vercel.app/dossier/_slug">Screenshot of /dossier/_slug</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/jcmUJsOi3shuOXZ6l0r8H9cn-nBCA9aJRuTxUMA2LqCY2CQLOtUL1DkF3QVRoGKJ5OuNticr_VLqCUqqNnMi8g.png">(view full size)</a> |







Commit 0a9a0379485bff5f06d915abce9799fbfbe1ef2c (https://portal-web-a6bq1n9c8-josa.vercel.app).

**Review by wissamataleh — APPROVED** [review]

**Pull request merged**
