### PR TITLE
Update the License

### LINKED ISSUE #131: Update CC license to Web version
**Link to Issue on portal-web-lagacy:** https://github.com/jordanopensource/portal-web-legacy/issues/234.

### PR DESCRIPTION
**Pull request by alsahawneh**
Fixes #131

### CODE REVIEW

**Comment by alsahawneh** [comment]
I'm still working on its design, but could you please take a look at it @mahasneh? 
Moreover, I have not added a link to the License, anchor tags act weirdly as block elements, any idea why?

**Review by mahasneh — CHANGES_REQUESTED** [review]
The main problem in this issue is that content is not discoverable using RDFa. From the old issue: 

> "Proper RDFa should be implemented [...] Information about implementing RDFa metadata for CC are available [here](https://wiki.creativecommons.org/wiki/RDFa#I.27m_a_developer.2C_how_do_I_implement_RDFa_into_my_platform.3F). Specifically, content discovery is possible through using the rel="license" attribute in an anchor tag linking to the CC license URL."

**Comment by alsahawneh** [comment]
Ready for review @mahasneh, unless you would like to change the design and/or the icon used.

**Review by mahasneh — APPROVED** [review]
Looks good

**Pull request merged**
